import Head from 'next/head'

// Components
import HomeHeroSection from '@/common/components/HomeHeroSection'

export default function Home() {
  return (
    <>
      <Head>
        <title>Contact Rolodex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>
      <HomeHeroSection />
    </>
  )
}
